osx_image: xcode7.3
sudo: false
language: objective-c
podfile: WPXMLRPCTest/Podfile
before_install:
# - gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=WPXMLRPCTest --no-repo-update
script:
- set -o pipefail && xcodebuild test -project wpxmlrpc.xcodeproj -scheme wpxmlrpc-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
